//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 09:03:09 AM CET 
//


package com.ericsson.eniq.stats.user.input.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.eniq.stats.user.input.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.eniq.stats.user.input.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimulationData }
     * 
     */
    public SimulationData createSimulationData() {
        return new SimulationData();
    }

    /**
     * Create an instance of {@link SimulationData.Simulation }
     * 
     */
    public SimulationData.Simulation createSimulationDataSimulation() {
        return new SimulationData.Simulation();
    }

}
